sudo: true

language: go

go:
  - "1.11.x"

service:
  - docker

jobs:
  include:
    - stage: build pub docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_nats_pub-dev
      - export VERSION=0.1.0
      - cd kubesim_nats_pub
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o nats-pub .
      - cd ..
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DHUBREPO:$VERSION -f images/kubesim_nats_pub/Dockerfile .
      - docker images
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:latest
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DHUBREPO
    - stage: build sub docker image
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_nats_sub-dev
      - export VERSION=0.1.0
      - cd kubesim_nats_sub
      - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o nats-sub .
      - cd ..
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DHUBREPO:$VERSION -f images/kubesim_nats_sub/Dockerfile .
      - docker images
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:latest
      - docker tag $DHUBREPO:$VERSION $DHUBREPO:travis-$TRAVIS_BUILD_NUMBER
      - docker push $DHUBREPO
    - stage: test
      script:
      - export DHUBREPO=$DOCKER_NAMESPACE/kubesim_nats_pub-dev
      - export VERSION=0.1.0
      - docker run -d -p 127.0.0.1:8080:80 --name hello $DHUBREPO:$VERSION
      - docker ps | grep -q hello
